steps:
  - label: preview dev
    commands:
      - ./preview.sh dev

  - label: preview uat
    commands:
      - ./preview.sh uat

  - label: preview prod
    commands:
      - ./preview.sh prod

  - wait

  - label: deploy dev
    commands:
      - ./deploy.sh dev

  - wait

  - label: deploy uat
    commands:
      - ./deploy.sh uat

  - wait

  - label: deploy prod
    commands:
      - ./deploy.sh prod
