steps:
  - label: preview dev
    commands:
      - preview.sh dev

  - label: preview uat
    commands:
      - preview.sh uat

  - wait

  - label: deploy dev
    commands:
      - deploy.sh dev

  - wait

  - label: deploy uat
    commands:
      - deploy.sh uat
